### ISSUE TITLE
Add support for destroying Blocks

### ISSUE THREAD

**Issue by theaddonn** [Bedrock-OSS/bedrock-boost#5]
There are a lot of ways to break blocks, but the Scripting API doesn't offer any direct way to destroy a block.
You surely can just run a command that makes this possible in the API, but adding a Polyfill for this might introduce the needed abstraction.

In my opinion a simple solution would be good enough, such as the following:
```ts
let block = world
    .getDimension("minecraft:overworld")
    .getBlock(Vec.from(0, 0, 0))
    .destroy({
        replacement: "air",
        drops: true,
        ...
     })
```

Would you consider this as useful/does this even make sense or is it just me being lazy and loving pretty abstractions?

**Comment by stirante** [comment]
Adding a new method to an existing type seems pretty annoying so that the autocomplete doesn't complain about it. It could fit into `CommandUtils` though.

**Comment by stirante** [comment]
Added in https://github.com/Bedrock-OSS/bedrock-boost/commit/6bd3ee6fe952b4c494a669e14c29527d3630f7a2
Did not add the option to set the old block handling, cause `destroy` is the only one, that makes sense. `keep` won't do anything and `replace` can be done probably faster with `setType('minecraft:air')`.

**Comment by theaddonn** [comment]
lovely!
